### PR TITLE
Added hovering effect to buttons

### LINKED ISSUE #33: Styling for the +1 -1 and Reset buttons
@Raghwendra-Dey  Sir, As of now there is no hovering state, active state stylings for the +1 -1 and Reset buttons.
I would like to add more styling to these buttons. Please assign me this issue :)

Thanks & Regards
Urvashi Anand

### PR DESCRIPTION
**Pull request by ghost**
fixes #33

### CODE REVIEW

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 its not working on `+Add` button of Todo list. Its still using that old CSS styling of buttons, make it like all the other currently available buttons in the project.

**Comment by ghost** [comment]
https://codepen.io/urvashi-code1255/pen/ExgyJoZ @Raghwendra-Dey  Sir is it Okay now?

**Comment by ghost** [comment]
add button
 looks like this

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 please modify this PR with these changes

**Comment by ghost** [comment]
Done @Raghwendra-Dey  Sir

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 could you please make the `+` before the ADD look like the `+` in the `+1` button? I mean make it look like `+ Add` with the beginning `+` like the one in `+1`
First post the photo here, then only modify the PR with the changes.

**Comment by ghost** [comment]
add button
 
Like this @Raghwendra-Dey Sir?

**Comment by Raghwendra-Dey** [comment]
@urvashi-code1255 no this is what it currently looks. Make the `+` of that button to look like the `+` of the `+1` button.

**Comment by ghost** [comment]
add button


Or like this? @Raghwendra-Dey Sir

**Comment by Raghwendra-Dey** [comment]
> add button
> 
> Or like this? @Raghwendra-Dey Sir

Like this. But put the `+` before `Add`

**Comment by ghost** [comment]
add button


Okay like this @Raghwendra-Dey

**Comment by Raghwendra-Dey** [comment]
> add button
> 
> Okay like this @Raghwendra-Dey

Yeah, its fine!!

**Comment by ghost** [comment]
Okay so can I add the changes? @Raghwendra-Dey  Sir

**Comment by Raghwendra-Dey** [comment]
> Okay so can I add the changes? @Raghwendra-Dey Sir

sure!!

**Comment by ghost** [comment]
Done @Raghwendra-Dey  Sir :)

**Pull request merged**
