### PR TITLE
Update HTML, JS, CSS and Remove scroll bar from todolist

### LINKED ISSUE #53: Make the Todo list scrollbar appear only when required
Make the Scrollbar of ToDo list only appear when its required, i.e. when the number of entries overflows the visible height of the list.

### LINKED ISSUE #56: Same Ids for different Element
Id is unique. We can't give **multiple ids to an element OR same id for multiple elements.** 
One more little thing I would like to mention is if it is centiseconds instead of miliseconds use `cs` instead of `ms`.

id error

I would like to work on this issue !! @Raghwendra-Dey Sir !!

### LINKED ISSUE #57: Should Avoid Inline Style & Class name should be meaningful.
In Real world Projects, we should avoid inline styling. Although we have given id here so we can do styling using id selector in style.css file. One more thing `=` is not meaningful class name. We should give some meaning classname.

inline style

### LINKED ISSUE #58: Using Html Element only in HTML file
Instead of adding ❤️ directly in index.html we should use `<i class="fas fa-heart"></i>`

heart

I am working on this issue @Raghwendra-Dey Sir.

### LINKED ISSUE #60: CSS Property Error
there is no property like `style`.

css property error

### PR DESCRIPTION
**Pull request by Vishal-raj-1**
# Description

## Update HTML 

* Adding Heart Icon & remove heart emoji And fixes #58 
* Remove Inline styling And Fixes #57 
* Give Class for timer, label, controls, hh, mm, ss. And Fixes #56 
* Remove scrollbar from Todo list, Now it Will appear only when required And Fixes #53 
* Add Missing </div> tag

## Update CSS

* Remove `style` from `footer <a>` and Fixes #60 
* Remove `overflow-y: auto` from todo container and it is not required. It is required in todo list.

## Update JavaScript

* Remove `querySelectorAll(......)[0]`. instead of that we can use `querySelector()`

@Raghwendra-Dey Sir, Review this PR. And don't forget to give your valuable feedback. 

Thanks & Regards 
Vishal

### CODE REVIEW

**Comment by Raghwendra-Dey** [comment]
Hey @Vishal-raj-1 thanks for working on checking validation sanity on the codebase.
Please center the `TODO` text and `Add` button in todo list. Like its currently is.

**Comment by Vishal-raj-1** [comment]
> Please center the `TODO` text and `Add` button in todo list. Like its currently is.
Sure !!

**Comment by Vishal-raj-1** [comment]
@Raghwendra-Dey Check Now!!

**Comment by Raghwendra-Dey** [comment]
> @Raghwendra-Dey Check Now!!

Also center the problem counter block. Its buttons and the text alignment.

**Comment by Vishal-raj-1** [comment]
@Raghwendra-Dey It's done

**Comment by Raghwendra-Dey** [comment]
@Vishal-raj-1 Should I merge it, or you want to make any further changes?

**Comment by Vishal-raj-1** [comment]
> @Vishal-raj-1 Should I merge it, or you want to make any further changes?

Merge this !! I will work on other issues

**Comment by Vishal-raj-1** [comment]
Thank you for merging @Raghwendra-Dey 🔥

**Pull request merged**
