### PR TITLE
-1 button bug fix

### LINKED ISSUE #101: Bug in avg time calculation
After #86 we can remove a problem, and thats taken time would be removed but theres some miscalculation due to this.
Follow these steps for reproducing the bug: (wait for suitable time according to your approximations)
* do `+1` to get avg of around 2 secs
* then do `+1` to make the avg 3-4 secs
* then do `+1` to make the avg 4-5 secs
* then remove do a `-1`, you should get avg to be 3-4 secs(prev value)
* then again do `-1` untill you get avg 0.
* then do a `+1` immediately after you have done the last `-1` which made the avg 0.
* you would see a much larger avg than expected. Since you have done the last `+1` immediately, it should have shown you a much smaller value(like maybe 0/1).

I think this is something to do with accumulation of all the previous times(I mean all the `+1`'s you did before all those times are getting added up). Maybe the starting time used during finding the time difference is not getting updated or maybe theres some variable which is also getting restored to the previous value which shouldn't have been.

### PR DESCRIPTION
**Pull request by Bbiswabasu**
Resolves #101

### CODE REVIEW

**Comment by Bbiswabasu** [comment]
@Raghwendra-Dey is this correct?

**Comment by Raghwendra-Dey** [comment]
Hey @Bbiswabasu its fine. Could you sync your patch with the recently merged PRs.

**Comment by Bbiswabasu** [comment]
I synced my fork before making this update. Did you mean anything else?

**Comment by Raghwendra-Dey** [comment]
> I synced my fork before making this update. Did you mean anything else?

No actually I recently merged #99 this is not in your patch.

**Comment by Bbiswabasu** [comment]
@Raghwendra-Dey done

**Comment by Raghwendra-Dey** [comment]
Could you explain, what was the problem before, with this syncing thing?
And yes, you should write `resolves` or `closes` or `fixes` #issue_number. Solve dont work.

**Pull request merged**
