### PR TITLE
Boilerplate code for todo list added

### PR DESCRIPTION
**Pull request by Bbiswabasu**
I have added todo_script.js and basic structure of it should look like. I have also made the container for todo list on which the tasks will show up. Solved #15

### CODE REVIEW

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu I think we need few more function shells right? 
1. Like one for when the little cross is pressed in and entry, which would delete that row from the list.
2. And One when the checkbox is clicked, which would strick that entry off. 
3. Also what have you thought about the checkbox thing? Like where it would go? obviously it would be created with the `AddTask` button, but need to handled separately when that is pressed right?

**Comment by Raghwendra-Dey** [comment]
And could you make this PR to the `todoList` branch, instead of `master`, since its a good practice to merge any feature to the master only when, its complete, not in the developmental stages.

**Comment by Bbiswabasu** [comment]
Since we are creating the elements dynamically, we can add onClick event listener for required elements inside the function addTask() (like inline function). So I didn't add any seperate function for that. The codes inside each event listener will probably be small.
Also, I am not sure how to strike through the text inside a textbox. It would be better if someone helps in doing this

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu Okay!! I got it. For that to do, two people have to work on the same thing at the same time. So, If you would be able to collaborate well with someone, it would be better. By making explicit functions we could have detached the works of different persons. But anyway, do it the way you would like to.
Maybe you can take @Ishan-Saini with you on this. If both of you are comfortable.
Feel free to contact me if theres any issues.

**Comment by Bbiswabasu** [comment]
I didn't think about that. It would be easier if we maintain seperate function for each element.

**Comment by Raghwendra-Dey** [comment]
Okay, then please add the required signatures for them in the boilerplate code, then we can divide the tasks.

**Comment by Ishan-Saini** [comment]
I am down for any type of collaboration. Please let me know

**Comment by Bbiswabasu** [comment]
I have made another PR on todoList branch. Should I close this one then?

**Comment by Raghwendra-Dey** [comment]
Yeah sure.

**Pull request closed without merging**
