### PR TITLE
Boilerplate code updated

### PR DESCRIPTION
**Pull request by Bbiswabasu**
I have made the template having separate functions for each events.

### CODE REVIEW

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu Please modify the comments inside `AddTask` function

**Comment by Bbiswabasu** [comment]
What modification should I make? I have made some changes in comments regarding when to call which function

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu okay thats fine we are good to go initially. Please open relevant issues regarding this.

**Comment by Bbiswabasu** [comment]
I will discuss with @Ishan-Saini and once we are done with who will do what, I will open relevant issues and proceed

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu If you guys need few more people then consider asking people who commented on that issue.

**Pull request merged**
