### PR TITLE
Block for difference of two timer added

### PR DESCRIPTION
**Pull request by Bbiswabasu**
I have solved issue #6 . It works perfect except for buggy case when Time devoted>Actual time

### CODE REVIEW

**Comment by Raghwendra-Dey** [comment]
I think you, misunderstood the issue, actually in the difference timer should show `Time Devoted - Actual Time Used`, not the other way round. And I think this patch is giving the other thing. 
Please once read [this](https://github.com/Bbiswabasu/productivity_meter#usage) part of the readme to clearly understand the purpose of this project, then I think you may understand, that why it shouldn't be `Actual Time Used - Time Devoted`.
Please change the difference timer formula to the aforementioned thing. And if possible, could you position the difference timer in the middle of the two timers, if you could tinker with the CSS a bit?

**Comment by Bbiswabasu** [comment]
Ok I will modify that

**Comment by Raghwendra-Dey** [comment]
Also @Bbiswabasu please introduce yourself to the community in the [gitter channel](https://gitter.im/productivity_meter/community), if you haven't done so.

**Comment by Bbiswabasu** [comment]
I think these latest changes will do the job as expected

**Pull request merged**
