### PR TITLE
Added the header and background

### LINKED ISSUE #16: Add a navbar in the header
For setting a basic layout, we will have to start from adding the top most thing a website requires for sure- A Navbar.

### PR DESCRIPTION
**Pull request by Nishant2907**
Kindly review the PR and tell if any changes are needed or not :)

Here's a screenshot of the header. The text in middle is moving in a typewriter format.

image

### CODE REVIEW

**Comment by Nishant2907** [comment]
Solved issue #16 .

**Comment by Raghwendra-Dey** [comment]
@Nishant2907 nice work. But I have few issues:
* For some reason, full quote is not getting loaded in my machine. Have a look at the ss below

Screenshot from 2020-12-08 23-58-53

* please put the image in a new folder named `assets` maybe.
* change the home button to `github` with github logo before the text. And link that to the github page of the project.
* Please remove the `How to use??` part of the footer, and instead add it before the `github` thing in the navbar, with an `i` icon in front of it. And naming it Usage. Link it to the usage section of the readme.
* Also currently theres no distinction between the navbar(which contains the produ.. text and the home button) and the body. Please make a clear distinction. Maybe you can give it some other styling, rather than using the same background image.
* The text colors are not that appealing, please change em.

**Comment by Nishant2907** [comment]
Hey @Raghwendra-Dey , I have done some updates
Kindly review them

**Comment by Raghwendra-Dey** [comment]
@Nishant2907 could you reduce the height of the navbar a bit?

**Comment by Nishant2907** [comment]
Yes sure, any more changes that need to be done?

**Comment by Raghwendra-Dey** [comment]
> Yes sure, any more changes that need to be done?

Nothing else. Please make the height which also looks good, and don't unncessarily hide the things below. I mean atleast you could see the whole difference block without scrolling.

**Comment by Raghwendra-Dey** [comment]
@Nishant2907 are you done with modifying the height?

**Comment by Raghwendra-Dey** [comment]
@Nishant2907 please resolve the merge conflicts.

**Comment by Nishant2907** [comment]
@Raghwendra-Dey , i have solved the merge issues, you can merge the PR now

**Comment by Raghwendra-Dey** [comment]
@Nishant2907 few things are messed up, like now, theres two footers, the pop up messages images are not getting loaded, like reset button's pop up message is not getting loaded, also, `-1` button's pop-up is also messed up.
I think, you messed them, while resolving the conflicts, I suggest you revert the last commit, and redo it carefully. Make sure, you don't mess up something which is already implemented. I suggest you keep the master repo files opened side by side for easy reference.

**Comment by Nishant2907** [comment]
Okay i am looking on it, but 1st thing I checked the file and found that getting two footers was not my fault. I got it from the fetch i did. So kindly check it once

**Comment by Raghwendra-Dey** [comment]
I cloned your patch, and it still shows two footers:

Screenshot from 2020-12-16 21-01-02

And since theres no footers in the master branch, so certainly those are introduced after your patch only.
Once check that you are up to date with this PR, on your local machine.
And also look into rest of the problems.

**Comment by Nishant2907** [comment]
Kindly check now, i hope it should work now.

**Comment by Raghwendra-Dey** [comment]
@Nishant2907 the pop-up message thing is still not fixed, and the footer still have the `How to use??` thing, which is supposed to go after your patch.
Please correct em.

**Comment by Nishant2907** [comment]
when i am checking, i am getting a popup on increasing or decreasing the amount of problems in the right corner of the screen. Can you show me how does the popup looks

**Comment by Raghwendra-Dey** [comment]
> when i am checking, i am getting a popup on increasing or decreasing the amount of problems in the right corner of the screen. Can you show me how does the popup looks

check the hosted site, after your patch those are not same as its there.

**Comment by Raghwendra-Dey** [comment]
here is what they look like in your patch:

Screenshot from 2020-12-16 22-20-45
Screenshot from 2020-12-16 22-21-05

**Comment by Nishant2907** [comment]
Kindly show, how it should look

**Comment by Raghwendra-Dey** [comment]
> Kindly show, how it should look

you can see the hosted site.

**Comment by Raghwendra-Dey** [comment]
If you need any help with the pop-up part, you may contact @kri-bhawna , and take her help. She worked on this.

**Comment by Nishant2907** [comment]
kindly check now, i hope it should work now

**Comment by Raghwendra-Dey** [comment]
> kindly check now, i hope it should work now

Its still not fixed.
One suggestion, always run your code yourself and ensure its correctness, before asking reviewers to see.

**Comment by Nishant2907** [comment]
image
its working for me.

**Comment by Raghwendra-Dey** [comment]
> image
> its working for me.

`+1` is working for me as well. `-1` is not working, also the `reset` is not working.

**Comment by Nishant2907** [comment]
Hey, i have checked the popup, its working now

**Comment by Raghwendra-Dey** [comment]
Sorry mate. Seems #64 broke the average time feature. I need to first get that fixed, then only I can merge this. Please hold untill that is done. Dont worry about the merge conflicts its showing now. Your patch is fine now, I will get #64 cleared then merge this.

**Comment by Raghwendra-Dey** [comment]
@Nishant2907 Thank you!

**Pull request merged**
