### PR TITLE
Updated pop_up_message

### PR DESCRIPTION
**Pull request by kri-bhawna**

### CODE REVIEW

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey  I have checked things from my side and found them working well. Please let me know if you also find everything well.
Sorry for the inconvenience.

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna please remove the console.log() statement somewhere. Its unecessarily spamming the console.

**Comment by Raghwendra-Dey** [comment]
Thank you @kri-bhawna for resolving the issues with the last PR.

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna could you explain what was the mistake, which was breaking the average time feature. #46 is also having the same issues, maybe be helpful to resolve this thing there as well.

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey While checking my js code with the master branch, I found two lines were missing in my js  file. On adding them, things started working perfectly. Maybe I deleted those lines by mistake or maybe I haven't used the most updated js code. These are the two possibilities.

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna what were those two lines?

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey 
if(isrunningAverage)
  {updateAverage(cnt);}
212 and 213 line no. of script.js

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna Thank you!

**Pull request merged**
