### PR TITLE
Updated pop-ups don't work

### LINKED ISSUE #78: The pop-ups dont work
Steps to reproduce the error:
* press `+1` button more than once(twice or thrice or ..) consecutively, without giving the pop-up time to fade away.
* Now, before it getting fade away, press the cross button on the pop-up.
* Now, if you again press the `+1` button any number of times, the pop-up for that wont function.

P.S: this is with all the four pop-ups, so the steps would be same, just replace the name of the button.

### PR DESCRIPTION
**Pull request by kri-bhawna**
fixes #78

### CODE REVIEW

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey  I have made the required changes and all the buttons are working well from my side. Please, do give the feedback.

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey Please check. I have resolved conflicts and checked the code, it is working well

**Comment by Raghwendra-Dey** [comment]
Hey @kri-bhawna theres some issues with your patch. I think the changes you did to resolve the conflicts introduced this bug.
If you press reset then the record buttons color turns white, which it's not supposed to.
Also never forget to check everything's working fine or not, on your side a well, before submitting anything for review.

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey  I resolved that bug, but since many other changes are merged, so I think I will have to make other changes as it is showing conflicting files. Will do so by today night itself

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna thats fine take your time to resolve them.

**Comment by kri-bhawna** [comment]
@Raghwendra-Dey  I have resolved conflicts. But since, I am not up to date with how recent changes work. Can you just do a favour of checking the updated one a last time. I have checked all previous glitches made by me. All are working well in my case

**Comment by Raghwendra-Dey** [comment]
@kri-bhawna LGTM.

**Comment by Raghwendra-Dey** [comment]
Hey @kri-bhawna could you explain the bug, which was causing that thing, and how did you resolved it.

**Pull request merged**
