### PR TITLE
Corrected the average time calculator

### LINKED ISSUE #89: Average not calculating properly
While calculating average, the thing that's going on now is that the previous average and the present number of problems are being used.

For better understanding this issue, do the following:
- First press the record button, add two tasks in six seconds, then stop recording
- Now add three more tasks
- Press record now again and add one task in six seconds
- Now stop the recording

If worked in a proper way the average has to be shown as (6 + 6) / 3 = 4s as only 3 problems have been done in 12 s recorded window , but what's happening is that (3[The previous avg]*5[No:of problems just before] + 6[New time] ) / 6[New count] = 3.5s 

Look into the issue....

### PR DESCRIPTION
**Pull request by rsriramc**
### PRs related/ Issues related

Closes #89 

### Work done

Displayed the +1 and -1 buttons only while the recording window is live, else they are not displayed

### Screen shots

image

#### When record is pressed

image

### CODE REVIEW

**Comment by Raghwendra-Dey** [comment]
Hey @ravisrc theres some problem with your patch. The changes after https://github.com/Raghwendra-Dey/productivity_meter/pull/86 is not showing in your patch.
Please have a look.

**Comment by rsriramc** [comment]
Are my changes not coming, or the changes made in the PR #86 not coming after my patch?

I can't see any such changes that did not show up.

**Comment by Raghwendra-Dey** [comment]
changes made by #86 not coming.

**Comment by rsriramc** [comment]
They changes were there, 
Try removing a problem, then the avg is set to prev value

**Comment by Raghwendra-Dey** [comment]
No, its not working. Try it once again.
You can also checkout the `script.js` file of the main repo and your this branch. The main repo contains the `deque` class and all. But your patch doesn't have them.

**Comment by rsriramc** [comment]
Yeah that's true but wont merging work?

**Pull request closed without merging**
