### PR TITLE
TodoList and Record Button is Styled

### LINKED ISSUE #32: Hovering effect to the Record button
As there is no pressing and hovering effect on the Record button(would be introduced after #20 ) yet, so add some hovering effects so that it will look like to be pressed when pressed.

### LINKED ISSUE #54: Give styling to the ToDo list
currently the Todo list `cross` button has no styling. Also the dimentions of the entries looks very odd, its too big. Also, the checkbox is too small. Correct these things, and give it a decent dimentions, along with styling it.

### PR DESCRIPTION
**Pull request by ghost**
fixes #32 
fixes #54

### CODE REVIEW

**Comment by ghost** [comment]
@Raghwendra-Dey Sir Please review this PR.

**Comment by Raghwendra-Dey** [comment]
Hey @urvashi-code1255 , thats a great work. 
The `Todo List` LGTM.
But there seems to be some issues with the record thing.
* It is supposed to be purple when off and blue when on right? But if you start it then its initally purple, but then once you make it blue by starting the recording, then if you stop, its not changing to purple.
* after pressing reset the record button turns completely white, which seems abnormal.

Rest seems to be okay, please have a look at these bugs.

**Comment by ghost** [comment]
@Raghwendra-Dey sir, I have corrected it, please check now.

**Comment by Raghwendra-Dey** [comment]
Hey @urvashi-code1255 , the reset button changing from blue to purple when turned off is yet not okay, could you have a look at that.
Press the record button to start recording, then switch it off, now you can't see the purple color, which should be signifying the off state.

**Comment by ghost** [comment]
Done @Raghwendra-Dey Sir now please check

**Comment by Raghwendra-Dey** [comment]
Hey @urvashi-code1255 I think theres some confusion. Theres still the same problem with the record button.
The record button currently shows blue color when ON and white when OFF. After your patch, its supposed to be showing purple when OFF and blue when ON, along with the hovering effect and hovering color of white(You may remove the hovering color change of white, thats not that necessary). 
But the problem is, Its intially showing purple, which it should be, since its OFF initially. but when I turn it ON, and it turns blue, then if I again turn it OFF, its not again getting converted to purple, which it should have been, instead, its showing blue always, no matter it is ON or OFF.

**Comment by ghost** [comment]
@Raghwendra-Dey Please check now...

**Comment by ghost** [comment]
@Raghwendra-Dey On my end It was Like when it is off then purple, on hover its white, when its on then blue and when again clicking to make it off then purple. Now, I have removed the hover effect.

**Comment by Raghwendra-Dey** [comment]
Oh crap! again its something to do with firefox, and chrome thing. Working on chrome, but not on firefox.
Please have a look what can be done.
Tip: always check you feature atleast on these two famous browsers.

**Comment by ghost** [comment]
@Raghwendra-Dey I have addressed the  problem background property was not working on firefox. I have changed it to backgroundColor. Now its working on both browsers on my side. Please check now :)

**Comment by Raghwendra-Dey** [comment]
Good work @urvashi-code1255 .

**Pull request merged**
