### PR TITLE
Behaviour for prb_minus added

### LINKED ISSUE #82: Update the Average time/problem, even when -1 is pressed
Currently the avg time/problem, is updated only when the +1 button, is pressed, but it doesn't do anything, when the -1 button is pressed. The problem was to save the delta time changes in the past problems, may blow up memory. But we may use a double ended Queue based solution for subtraction of one problem from the problem counter, and still showing the correct average time per problem. And keeping a max_capacity variable, and keep it to something like, 100, so, its highly unlikely, that a user would press -1 consecutively 100 times, And if the size of the deque becomes greater than the max_capacity, then pop-out elements from the front(which are the least recently used ones).
When the user presses -1 you would pop-out elements from the back, which are the recent time delta, and update the average accordingly, using that value.
If the deque is empty, then you may, do nothing. Later on we can implement a pop-up warning for the user, that `decreasing problem count further might result in faulty avg time`.

### PR DESCRIPTION
**Pull request by Bbiswabasu**
resolves #82 . Due to formatting document, it shows a lot of changes. But actually, I have made changes only to functions associated with problem counter only.

### CODE REVIEW

**Comment by Bbiswabasu** [comment]
@Raghwendra-Dey I have resolved the conflicts

**Comment by Raghwendra-Dey** [comment]
Hey @Bbiswabasu theres some issues with your patch, since, after your patch, the record button's color change is not functioning as expected.
Please have a look, and also never forget to check everything to be working fine, from your end as well.

**Comment by Bbiswabasu** [comment]
@Raghwendra-Dey  this latest update is working fine from my side. I think earlier I messed up something while resolving the conflicts

**Comment by Raghwendra-Dey** [comment]
Hey @Bbiswabasu still theres this problem of record button getting white, when reset is pressed or when it is switched OFF.
Don't forget to check it for firefox as well.

**Comment by Bbiswabasu** [comment]
@Raghwendra-Dey  it is working fine on both chrome & firefox

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu have a look at this, after I pressed reset:

Screenshot from 2020-12-31 21-23-00

**Comment by Bbiswabasu** [comment]
In your screenshot, the layout of the two buttons is slightly different. I think there has been some change in other files by other contributors which I didn't pull. Probably that is causing the problem. Let me check once

**Comment by Raghwendra-Dey** [comment]
Yeah! probably.

**Comment by Bbiswabasu** [comment]
@Raghwendra-Dey  plz check once if reset & record buttons are still behaving correctly with respect to problem counter or not. I think the problem which you showed is related to usage of Bootstrap

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu theres still conflicts with the `script.js`

**Comment by Bbiswabasu** [comment]
I can't understand what is the problem. Everytime I am updating the file with my latest code but still it is showing conflicts. Can you guide me regarding what to do or why conflicts actually happen?

**Comment by Raghwendra-Dey** [comment]
@Bbiswabasu regarding why conflicts arise you can read [this](https://www.atlassian.com/git/tutorials/using-branches/merge-conflicts).
And for resolving merge conflicts I generally use the online editor of github, since If I do it in my local copy then I might need to pull the recent changes, well ofc you can do that.
And for now, I think, the recently merged PRs are creating problems, since, you are working and on the same time, some other merges are taking place.
Now, theres no such PRs. Now try once more, I think this time you would be good to merge.

**Comment by Bbiswabasu** [comment]
@Raghwendra-Dey plz check once more. I hope now it will work perfect.

**Comment by Raghwendra-Dey** [comment]
Yeah! good work @Bbiswabasu !
But we could have optimised the operations of the `deque`, by using linked list or circular arrays. But anyways, let it be the way it is for now.

**Pull request merged**
